### ISSUE TITLE
it's possible to be fast and slow at the same time

### ISSUE THREAD

**Issue by andrewrk** [thejoshwolfe/legend-of-swarkland#38]
![screenshot_2016-12-07_22-39-30](https://cloud.githubusercontent.com/assets/106511/20996780/230a3c78-bcce-11e6-8eb3-b8ad10611ee0.png)

**Comment by thejoshwolfe** [comment]
See also #30.

Here's an idea: You can be fast and slow at the same time, and it's a special state where your speed flickers intermittently about a wide range of values. This will solve #30's problem where information should be unambiguous, and is a little more interesting than speed curing slowing. Each of speed and slowing would have their own timeout, so once one of them runs out the jittery speed effect would devolve into the remaining of speed or slowing effect (and probably usually slowing, since it tends to have a longer timeout).

**Comment by thejoshwolfe** [comment]
I don't like the above idea anymore. I think it'd be better if speed and slowing cancel each other out, like was originally intended.
